name: premier
description: premier

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 11.0.0+11

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #For StateManagement And Root
  freezed_annotation: ^2.2.0
  stacked: ^2.3.15+1
  stacked_services: ^0.9.5
  intl: ^0.18.0
  in_app_update: ^4.0.1
  firebase:
  firebase_core: ^2.3.0
  firebase_messaging:
  flutter_local_notifications: ^16.3.0

  #External Api
  permission_handler: ^10.3.0
  version: ^2.0.0
  connectivity_plus: ^3.0.3
  package_info: any

  shared_preferences: ^2.0.17
  google_maps_flutter: ^2.2.3

  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  device_info_plus: ^7.0.0
  provider:
  #For UI
  hexcolor: ^3.0.1
  cherry_toast: ^1.0.9
  cached_network_image: ^3.2.3
  pie_chart: ^5.3.2
  barcode_widget: ^2.0.3
  map_launcher: ^2.5.0+1
  cloudinary: ^1.1.0
  image_picker: ^0.8.6+3
  url_launcher: ^6.1.10
  dropdown_search: ^5.0.6
  pdf: ^3.8.4
  path_provider: ^2.0.13
  open_file_safe: ^3.2.3
  flutter_background_service:
  app_settings: ^4.2.0
  widget_to_marker: ^1.0.3
  fl_chart:
  percent_indicator:

dependency_overrides:
  ffi: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  package_rename: ^1.0.0+1
  stacked_generator: ^0.8.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/sup5.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

package_rename_config:
  android:
    app_name: Premier Super App
    bundle_name: premiersuperapp
    package_name: com.premier.superapp

  ios:
    app_name: Premier Super App
    bundle_name: premiersuperapp
    package_name: com.premier.superapp

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 800
          style: italic
